version: '3'
services:
  service_imperativa:
    container_name: service_imperativa
    image: quarkus/mongodb-panache-quickstart
    ports:
    - 8082:8082
    networks:
      - backend
networks:
  backend:
    driver: "bridge"